version: '3'

services:
  app:
    container_name: my-app-003
    image: my-app:0.1
    environment:
      - ENVIRONMENT=development
      - PORT=8080
    ports:
      - '5003:8080'
    volumes:
      - "./app:/app"
  redis:
    container_name: redis
    image: redis
    environment:
      - ENVIRONMENT=development
