version: '3'

services:
  app:
    container_name: my-app-004
    image: my-app:0.1
    environment:
      - ENVIRONMENT=development
      - PORT=8080
    ports:
      - '5004:8080'
    volumes:
      - "./app:/app"
  redis:
    container_name: redis
    image: redis
    environment:
      - ENVIRONMENT=development
  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: soopersekret
